# Generated by Django 5.2.7 on 2025-10-08 13:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('economy_seats', models.PositiveIntegerField(default=0)),
                ('business_seats', models.PositiveIntegerField(default=0)),
                ('firstclass_seats', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['airline'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('IND', 'India'), ('SING', 'Singapore'), ('JPN', 'Japan')], max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_international', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_refundable', models.BooleanField(default=False)),
                ('seat_selection', models.BooleanField(default=False)),
                ('meal_included', models.BooleanField(default=False)),
                ('baggage_allowance_kg', models.PositiveIntegerField(default=0)),
                ('extra_baggage_allowed', models.BooleanField(default=False)),
                ('priority_boarding', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FlightClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_email', models.EmailField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='airline_logos/')),
                ('country', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('gstin_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FlightClassFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fare_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.faretype')),
                ('flight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='flights.flightclass')),
            ],
            options={
                'unique_together': {('flight_class', 'fare_type')},
            },
        ),
        migrations.CreateModel(
            name='FlightRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('is_direct', models.BooleanField(default=False)),
                ('operational_days', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flights.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flights.airport')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='FlightLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leg_arrivals', to='flights.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leg_departures', to='flights.airport')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='flights.flightroute')),
            ],
            options={
                'ordering': ['stop_order'],
            },
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', help_text='Current status of the flight', max_length=12)),
                ('delay_minutes', models.PositiveIntegerField(blank=True, help_text='If delayed, number of minutes delayed', null=True)),
                ('rescheduled_to', models.DateTimeField(blank=True, help_text='New datetime if flight is rescheduled', null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.aircraft')),
                ('flight_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='flights.flightleg')),
            ],
        ),
        migrations.AddField(
            model_name='flightclass',
            name='scheduled_flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='flights.flightschedule'),
        ),
        migrations.CreateModel(
            name='FlightSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('is_booked', models.BooleanField(default=False)),
                ('flight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.flightclass')),
                ('flight_class_fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightclassfare')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('infant', 'Infant')], default='adult', max_length=10)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian', models.ForeignKey(blank=True, limit_choices_to={'passenger_type': 'adult'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='flights.passenger')),
            ],
        ),
        migrations.AddField(
            model_name='aircraft',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.serviceprovider'),
        ),
    ]
