# Generated by Django 5.2.7 on 2025-10-11 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_serviceprovider'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='flightroute',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='delay_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=12),
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gates', models.PositiveIntegerField(default=0, help_text='Number of gates in the terminal')),
                ('is_international', models.BooleanField(default=False)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='flights.airport')),
            ],
        ),
        migrations.AddField(
            model_name='flightleg',
            name='destination_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arriving_flights', to='flights.terminal'),
        ),
        migrations.AddField(
            model_name='flightleg',
            name='origin_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departing_flights', to='flights.terminal'),
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
    ]
