# Generated by Django 5.2.7 on 2025-10-13 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='flightroute',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.serviceprovider'),
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='flights.airport')),
            ],
            options={
                'ordering': ['airport', 'name'],
                'unique_together': {('airport', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
    ]
