# Generated by Django 5.2.7 on 2025-10-12 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_airline'),
        ('flights', '0002_alter_aircraft_airline_alter_flightroute_airline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.airline'),
        ),
        migrations.AlterField(
            model_name='flightroute',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.airline'),
        ),
    ]
