# Generated by Django 5.2.7 on 2025-10-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_aircraft_airline_alter_flightroute_airline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightclass',
            name='name',
            field=models.CharField(choices=[('economy', 'Economy'), ('Buisness', 'Buisness'), ('First Class', 'First Class')], max_length=15),
        ),
    ]
