# Generated by Django 5.2.7 on 2025-10-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_flightclass_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ['airport', 'name']},
        ),
        migrations.RemoveField(
            model_name='flightleg',
            name='destination_terminal',
        ),
        migrations.RemoveField(
            model_name='flightleg',
            name='origin_terminal',
        ),
        migrations.AlterUniqueTogether(
            name='terminal',
            unique_together={('airport', 'name')},
        ),
        migrations.AddField(
            model_name='terminal',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flightclass',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='delay_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='If delayed, number of minutes delayed', null=True),
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', help_text='Current status of the flight', max_length=12),
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='gates',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='is_international',
        ),
    ]
